// Seed success stories / role models
// Based on research: Students are motivated by relatable success stories
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SUCCESS_STORIES = [
  {
    name: 'Sarah Martinez',
    age: 24,
    occupation: 'Graduate Student',
    region: 'US',
    goalType: 'emergency_fund',
    goalTitle: 'Built $5,000 Emergency Fund in 14 Months',
    startingPoint: 'Started with $0 savings and $15k in student loans. Was living paycheck to paycheck.',
    achievement: 'Saved $5,000 emergency fund while making minimum student loan payments.',
    amountSaved: 5000,
    timeframe: 14,
    monthlyContribution: 357,
    story: `When I graduated, I had no savings and $15k in student loans. Every unexpected expense went on my credit card. After my car broke down and I couldn't afford the repair, I realized I needed to change. I started tracking every expense in a simple spreadsheet. I cut my grocery budget by meal prepping ($200/month savings) and canceled subscriptions I didn't use ($45/month). I picked up weekend tutoring gigs that brought in an extra $150-200/month. It was slow at first - some months I could only save $200. But I stayed consistent. After 14 months, I hit $5,000. Now when my laptop died, I paid cash instead of going into debt. That feeling is priceless.`,
    challenges: [
      'Unpredictable expenses kept derailing progress',
      'Friends wanted to go out and I felt left out',
      'Side hustle income varied month to month',
      'Almost gave up after 6 months when progress felt slow',
    ],
    strategies: [
      'Automated transfers of $100/week to savings (out of sight, out of mind)',
      'Found free social activities: hiking, game nights at home',
      'Used "found money" rule: tax refund, gifts, bonuses all went to savings',
      'Tracked progress visually with a chart on my wall',
      'Celebrated milestones: $1k, $2.5k, $5k with small rewards',
    ],
    keyTakeaway: 'Small consistent actions beat big sporadic efforts. Even $50/week adds up. The key is making it automatic so you don\'t have to rely on willpower.',
    featured: true,
    verified: true,
    inspirationScore: 95,
  },
  {
    name: 'Marcus Thompson',
    age: 22,
    occupation: 'Junior Software Developer',
    region: 'US',
    goalType: 'debt_free',
    goalTitle: 'Paid Off $8,000 Credit Card Debt in 10 Months',
    startingPoint: 'Graduated with $8,000 in credit card debt from college expenses and poor money habits.',
    achievement: 'Completely debt-free with $1,500 in savings.',
    amountSaved: 9500,
    timeframe: 10,
    monthlyContribution: 950,
    story: `My credit card debt snowballed during college. Between textbooks, car repairs, and going out, I maxed out at $8,000. After graduation, I got a decent job ($50k salary) but felt trapped by the debt. I tried budgeting apps but nothing stuck until I saw how much interest I was paying: $140/month going nowhere! I got angry and motivated. I moved back with my parents temporarily (swallowed my pride), which saved $1,200/month in rent. I sold my gaming PC and other stuff I didn't need ($800). I worked overtime and side projects whenever possible. Every dollar beyond essentials went to the debt. Watching that balance drop each month became addicting. Month 10, I made the final $600 payment. Best feeling ever.`,
    challenges: [
      'Felt embarrassed about living at home at 22',
      'Missing out on social events to save money',
      'Temptation to slow down payments and enjoy life',
      'Credit score was damaged, felt discouraging',
    ],
    strategies: [
      'Debt avalanche method: attacked highest interest card first',
      'Used "round-up" strategy: $47 purchase? Paid $50, $3 to debt',
      'Made debt tracker my phone wallpaper',
      'Told close friends about my goal so they\'d support me',
      'Rewarded myself with free activities after each $1k paid off',
    ],
    keyTakeaway: 'Sometimes you have to make temporary sacrifices (like living at home) for long-term freedom. The emotional weight of debt is heavier than any sacrifice. Freedom is worth it.',
    featured: true,
    verified: true,
    inspirationScore: 92,
  },
  {
    name: 'Emily Chen',
    age: 26,
    occupation: 'Marketing Coordinator',
    region: 'CA',
    goalType: 'travel',
    goalTitle: 'Saved $7,000 for Europe Trip in 18 Months',
    startingPoint: 'Always dreamed of backpacking Europe but never had the money. Made $42k/year.',
    achievement: 'Saved $7,000 and spent 2 months traveling through 8 countries.',
    amountSaved: 7000,
    timeframe: 18,
    monthlyContribution: 389,
    story: `I'd been saying "someday I'll travel" for years. Then my grandmother passed away, and I realized someday might never come. I set a specific goal: $7,000 for a 2-month Europe trip. I created a separate savings account called "Europe Adventure" and set up automatic transfers every payday. I got creative with earning more: freelance graphic design ($300-500/month), sold my clothes on Poshmark, did market research studies. On the spending side, I did a "no-spend month" challenge quarterly where I only bought groceries and essentials. I packed lunch every day (saved $200/month). I unsubscribed from marketing emails so I wasn't tempted. Every $500 saved, I'd research one more destination - kept me motivated. At 18 months, I had $7,200 and booked my flight. That trip changed my life.`,
    challenges: [
      `FOMO when friends went on spontaneous trips`,
      `Freelance income wasn't guaranteed every month`,
      `Tempted to use savings for "smaller" trips`,
      `Family questioned why I didn't use money for "practical" things`,
    ],
    strategies: [
      'Made goal visible: travel photos vision board on my fridge',
      'Used "pay yourself first" rule: savings came before any spending',
      'Found cheap entertainment: free museum days, picnics, hiking',
      'Joined "buy nothing" local group for free stuff',
      'Told everyone about my goal - accountability and they stopped inviting me to expensive things',
    ],
    keyTakeaway: 'Having a specific, emotional goal makes saving easier. When you can visualize the end result (walking through Paris, eating gelato in Rome), saying no to daily temptations becomes natural.',
    featured: false,
    verified: true,
    inspirationScore: 88,
  },
  {
    name: 'James Wilson',
    age: 25,
    occupation: 'Teacher',
    region: 'UK',
    goalType: 'house',
    goalTitle: 'Saved £15,000 House Deposit in 3 Years',
    startingPoint: 'Teacher making £28k/year, renting a flat, felt like homeownership was impossible.',
    achievement: 'Saved £15,000 deposit, bought first flat with partner.',
    amountSaved: 15000,
    timeframe: 36,
    monthlyContribution: 417,
    story: `On a teacher's salary in London, buying a house felt like a fantasy. But I was tired of rent increasing every year. I opened a Lifetime ISA and put in the max (£4,000/year) to get the 25% government bonus. That's free money! I moved to a cheaper area (Zone 4 instead of Zone 2), saving £300/month. I biked to work instead of taking the tube (£135/month saved). My partner and I combined our savings goal, which made it feel more achievable. We stopped eating out - we'd have "restaurant night" at home once a week where we'd cook fancy meals. We cut our food budget in half by switching to Aldi. Some months we could save £600, others only £200. But year by year, we watched the balance grow. After 3 years and £15k saved, we bought a flat. Our mortgage is actually less than our old rent!`,
    challenges: [
      'London housing prices kept rising faster than savings',
      'Felt isolated living further from friends',
      'Partner sometimes wanted to quit and just enjoy life',
      'Unexpected expenses (laptop died, wedding gifts) ate into budget',
    ],
    strategies: [
      'Maxed Lifetime ISA for 25% government boost',
      'Automated savings: direct debit right after payday',
      'Used "52-week challenge": save £1 week 1, £2 week 2, etc.',
      'Kept savings in separate bank so not tempted',
      'Celebrated every £1,000 milestone with cheap date night',
    ],
    keyTakeaway: 'Use every advantage available: government bonuses, employer matches, tax benefits. They\'re free money. And having a partner/accountability buddy makes the journey less lonely.',
    featured: true,
    verified: true,
    inspirationScore: 90,
  },
  {
    name: 'Priya Patel',
    age: 23,
    occupation: 'Nursing Student',
    region: 'US',
    goalType: 'car',
    goalTitle: 'Saved $6,000 to Buy First Car in Cash',
    startingPoint: 'Relied on unreliable public transit and rideshares. Needed a car for nursing clinicals.',
    achievement: 'Bought reliable used Honda Civic for $6,000 cash - no car payment!',
    amountSaved: 6000,
    timeframe: 12,
    monthlyContribution: 500,
    story: `As a nursing student, I needed a car to get to clinical rotations at 5am. I couldn't afford a car payment on top of tuition, so I decided to save up and buy cash. I worked as a waitress 3 nights a week (brought in $400-600/week). Every tip over $100 per shift went straight to my car fund. I lived with roommates to keep rent cheap ($450/month). I borrowed textbooks from the library instead of buying. I meal prepped everything - spent maybe $40/week on groceries. I didn't buy new clothes for a year (borrowed from friends). I made a spreadsheet showing my progress and shared it with my family - they became my cheerleaders. Some friends didn't understand why I didn't just finance a car, but I didn't want a payment hanging over me during school. After 12 months of hustle, I had $6,300. Found a great 2015 Honda Civic with 80k miles for $6,000. Having a paid-off car gave me so much peace of mind.`,
    challenges: [
      'Working late nights while in nursing school was exhausting',
      'Car prices kept rising, felt like moving target',
      'Friends judged me for not having a car sooner',
      'Tempted to just finance and have car immediately',
    ],
    strategies: [
      'Used "income buckets": wages for expenses, tips for car savings',
      'Kept savings at a separate bank with no debit card',
      'Watched YouTube videos about car buying to stay motivated',
      'Used free entertainment only: campus events, parks, movie nights',
      'Researched cars obsessively - made the goal feel real',
    ],
    keyTakeaway: 'Avoiding debt payments gives you so much more freedom. A car payment might seem manageable, but buying cash means no stress, no interest, full ownership. Future me thanks past me every day.',
    featured: false,
    verified: true,
    inspirationScore: 87,
  },
  {
    name: 'Alex Rivera',
    age: 27,
    occupation: 'Retail Manager',
    region: 'US',
    goalType: 'emergency_fund',
    goalTitle: 'Built $10,000 Emergency Fund While Paying Off Debt',
    startingPoint: 'Had $12k student loans, no savings, making $38k/year. Living paycheck to paycheck.',
    achievement: 'Built full 6-month emergency fund while paying $5k toward debt.',
    amountSaved: 10000,
    timeframe: 24,
    monthlyContribution: 417,
    story: `After getting laid off during COVID and having zero savings to fall back on, I promised myself I'd never be in that position again. I landed a retail management job making $38k. Everyone said "pay off debt first" but I wanted security, so I split my extra money: 60% to emergency fund, 40% to debt. I worked retail, so I picked up every extra shift offered. I negotiated a raise after 8 months (got $2k more). I moved to a cheaper apartment ($200/month saved). I used cashback apps religiously - made about $40/month. I stopped financing anything - paid cash or didn't buy it. It took 2 years, but I now have $10k in savings AND paid off $5k of debt. When my hours got cut this year, I didn't panic. That peace of mind is priceless.`,
    challenges: [
      'Conflicting advice: some said emergency fund first, others said debt',
      'Retail schedule made side hustles hard',
      'Progress felt slow splitting money two ways',
      'Got COVID mid-journey, had to pause savings for 2 months',
    ],
    strategies: [
      'Split strategy: 60% savings, 40% debt until emergency fund built',
      'Used high-yield savings account (earning 4.5% interest)',
      'Set up "save the raise" rule: new income went straight to goals',
      'Used envelope method for discretionary spending',
      'Checked r/personalfinance daily for motivation',
    ],
    keyTakeaway: 'Don\'t let perfect be the enemy of good. Everyone has opinions on "the right way," but the best strategy is the one you\'ll stick to. Splitting between savings and debt worked for my peace of mind.',
    featured: false,
    verified: true,
    inspirationScore: 85,
  },
  {
    name: 'Olivia Brown',
    age: 21,
    occupation: 'College Senior',
    region: 'US',
    goalType: 'emergency_fund',
    goalTitle: 'Saved $2,000 Emergency Fund in 8 Months as Full-Time Student',
    startingPoint: 'Full-time student working part-time at campus library, making $12/hour, 15 hours/week.',
    achievement: 'Built starter emergency fund of $2,000 before graduation.',
    amountSaved: 2000,
    timeframe: 8,
    monthlyContribution: 250,
    story: `I'm a senior in college and saw too many friends go into credit card debt when their laptops broke or cars needed repairs. I wanted a safety net before graduating into the "real world." I made maybe $720/month from my library job. I committed to saving $50/week no matter what. I used student discounts for everything (saved on Spotify, Amazon, software). I cooked in my dorm - instant pot meals cost $2-3 each. I sold old textbooks and clothes online. I tutored other students for $20/hour (made an extra $100-200/month). I skipped spring break trip and stayed home (saved $600). Every birthday check from family went straight to savings. My friends thought I was crazy, but I wanted to graduate with ZERO debt and some savings. Mission accomplished! I have $2,000 saved, no credit card debt, and $10k in student loans (could've been worse). Starting my job in July with a cushion feels amazing.`,
    challenges: [
      'Making minimum wage made it feel impossible',
      'FOMO watching friends go on trips',
      'Unexpected expenses (speeding ticket, medical co-pay)',
      'Part-time hours got cut during winter break',
    ],
    strategies: [
      'Used "pay yourself first": $50 to savings every week before anything else',
      'Kept savings in different bank without debit card access',
      'Used campus free food events for meals',
      'Bought nothing new - thrifted or borrowed everything',
      'Made it a game: challenged myself to save $1 more each week',
    ],
    keyTakeaway: 'You don\'t need a high income to start saving. Even on minimum wage, $50/week is doable. Starting young means you\'ll build the habit early. Every dollar counts when you\'re building from zero.',
    featured: true,
    verified: true,
    inspirationScore: 93,
  },
  {
    name: 'Daniel Kim',
    age: 28,
    occupation: 'Graphic Designer',
    region: 'CA',
    goalType: 'debt_free',
    goalTitle: 'Paid Off $25,000 Student Loans in 2.5 Years',
    startingPoint: 'Graduated with $25k in student loans, making $45k salary, felt overwhelmed.',
    achievement: 'Completely debt-free, saved $3,000 emergency fund simultaneously.',
    amountSaved: 28000,
    timeframe: 30,
    monthlyContribution: 933,
    story: `I graduated with a "normal" amount of student debt - $25k. Everyone said "just pay the minimum over 10 years," but I hated the idea of debt hanging over me for a decade. I made a plan: pay it off in 3 years. I tracked every expense obsessively. I discovered I was spending $400/month on food delivery - that stopped immediately. I negotiated my salary (got $5k raise). I took on freelance design projects at night and weekends ($800-1200/month extra). I lived with roommates even though I wanted my own place. I drove a beat-up Honda instead of buying a new car. I used the debt avalanche method, targeting the highest interest loan first. Watching the principal drop became my entertainment. Some months I'd throw an extra $1,500 at it. After 2.5 years, I made the final payment of $800. I literally cried. Now that $1,000+/month goes to investing and building wealth instead of interest payments.`,
    challenges: [
      'Freelance work on top of full-time job led to burnout',
      'Felt behind peers who were buying houses, cars',
      'Interest kept accruing, felt like running on a treadmill',
      'Friends didn\'t understand my "obsession" with debt',
    ],
    strategies: [
      'Used debt avalanche: highest interest rate first',
      'Made bi-weekly payments instead of monthly (extra payment per year)',
      'Put tax refunds, bonuses, freelance income 100% toward debt',
      'Used Mint to track every penny',
      'Joined "debt-free community" online for motivation',
    ],
    keyTakeaway: 'Paying off debt fast requires sacrificing now for freedom later. Those 2.5 years weren\'t always fun, but now I\'m 28, debt-free, and building wealth. My friends with 7+ years of payments left are jealous.',
    featured: false,
    verified: true,
    inspirationScore: 86,
  },
  {
    name: 'Sophie Anderson',
    age: 24,
    occupation: 'Restaurant Server',
    region: 'US',
    goalType: 'emergency_fund',
    goalTitle: 'Saved $3,500 Emergency Fund on Variable Income',
    startingPoint: 'Server with wildly variable income ($1,200-2,400/month). No savings, lived tip-to-tip.',
    achievement: 'Built $3,500 emergency fund despite unpredictable income.',
    amountSaved: 3500,
    timeframe: 11,
    monthlyContribution: 318,
    story: `Working as a server means some days I make $200 in tips, other days $40. I never knew what my paycheck would be, which made budgeting impossible. But after my car broke down and I couldn't afford the $800 repair, I knew I needed savings. I started tracking my tips daily in a notebook. I calculated my average monthly income over 3 months: $1,800. I budgeted off 80% of that ($1,440) and saved every dollar above that. Good weekend? Extra $100 went to savings. Slow week? I at least hit my baseline budget. I worked double shifts whenever possible. I stopped going out after work (servers love late-night food - was spending $300/month). I packed meals for my shifts. I moved to a cheaper apartment with 2 roommates ($250/month saved). Some months I saved $500, others $150. But it added up. After 11 months, I had $3,500. When a regular customer asked me to cater their party (paid $600), I could finally say yes because I had savings as a safety net.`,
    challenges: [
      'Variable income made consistent saving hard',
      'Pressure from coworkers to go out after shifts',
      'Winter months were always slow, less tips',
      'Cash tips were tempting to spend immediately',
    ],
    strategies: [
      'Tracked tips daily, calculated monthly averages',
      'Budgeted off 80% of average income, saved the rest',
      'Used envelope method: cash tips went into physical envelopes',
      'Saved all cash tips, spent only paycheck',
      'Created "bad month" buffer in budget for slow periods',
    ],
    keyTakeaway: 'Variable income doesn\'t mean you can\'t save - it just requires tracking and averaging. Budget for your low months, save the difference in high months. Consistency matters more than the amount.',
    featured: false,
    verified: true,
    inspirationScore: 84,
  },
  {
    name: 'Tom Hughes',
    age: 26,
    occupation: 'Sales Associate',
    region: 'UK',
    goalType: 'travel',
    goalTitle: 'Saved £4,000 for Southeast Asia Trip in 10 Months',
    startingPoint: 'Working retail making £22k/year. Wanted to travel before settling into a career.',
    achievement: 'Saved £4,000 and spent 3 months traveling Thailand, Vietnam, and Bali.',
    amountSaved: 4000,
    timeframe: 10,
    monthlyContribution: 400,
    story: `I was 25 and felt stuck in retail. All my friends were traveling and posting amazing photos, while I was counting pennies. I decided: in 10 months, I'm going to Southeast Asia for 3 months. No excuses. I opened a separate savings account called "Asia Adventure." I set up a standing order: £100/week automatically transferred the day after payday. I took on extra shifts and bank holidays (time and a half). I cancelled gym (£45/month), streaming services (£20/month), and meal delivery kit (£40/month). I moved back to my parents' house for 6 months (saved £500/month rent). I sold my car since I wasn't using it (got £2,000). I stopped buying lunch at work - brought sandwiches (saved £100/month). I didn't buy any new clothes for 10 months. Every pound saved felt like a day in paradise. After 10 months I had £4,200. I quit my job and spent 3 months in Southeast Asia. Best decision of my life. Came back refreshed and ready to start a new career.`,
    challenges: [
      'Living with parents at 25 felt like moving backward',
      'Friends judged me for "throwing away money on travel"',
      'Tempted to use savings for "smaller" UK trips',
      'Worried about job gap on resume',
    ],
    strategies: [
      'Automated savings: standing order every week',
      'Sold car (wasn\'t using it, insurance was expensive)',
      'Moved home temporarily (tough but saved £500/month)',
      'Used matched betting to make extra £200-300/month legally',
      'Joined travel forums to stay motivated and learn budget tips',
    ],
    keyTakeaway: 'Sometimes you have to make uncomfortable choices (like moving home) to achieve big goals. Three months of travel was worth 10 months of sacrifice. Experiences > stuff, always.',
    featured: false,
    verified: true,
    inspirationScore: 82,
  },
];

async function main() {
  console.log('Starting success stories seeding...');

  // Clear existing stories in development
  await prisma.successStory.deleteMany({});

  // Create all stories
  for (const story of SUCCESS_STORIES) {
    await prisma.successStory.create({
      data: story,
    });
  }

  const count = await prisma.successStory.count();
  console.log(`✅ Success stories seeding completed! Total Stories: ${count}`);
}

main()
  .catch((e) => {
    console.error('Error seeding success stories:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
