/**
 * Seed Script for Financial Products
 *
 * Creates 25+ realistic financial products with dual benefits:
 * - High-yield savings accounts
 * - Credit-builder cards
 * - Student checking accounts
 * - Investment platforms
 * - ISAs (UK)
 *
 * Run with: npx tsx scripts/seed-financial-products.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting financial products seeding...\n');

  // Clean existing data
  console.log('Cleaning existing products data...');
  await prisma.productRecommendation.deleteMany({});
  await prisma.financialProduct.deleteMany({});
  console.log('✓ Cleaned existing data\n');

  const products = [
    // High-Yield Savings Accounts (US)
    {
      name: 'Marcus by Goldman Sachs High Yield Savings',
      provider: 'Goldman Sachs',
      productType: 'savings_account',
      region: 'US',
      interestRate: 5.4,
      apr: null,
      fees: { monthly: 0, minimum: 0, withdrawal: 0 },
      description: 'Industry-leading interest rate with no fees and no minimum balance. FDIC insured up to $250,000.',
      keyFeatures: [
        '5.4% APY on all balances',
        'No monthly fees or minimum balance',
        'Easy online transfers',
        'FDIC insured',
        'No maximum balance limit',
      ],
      primaryBenefit: 'Earn 5.4% on your savings',
      secondaryBenefit: 'Build disciplined saving habits with automatic transfers',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'Available to all US residents 18+',
      applicationUrl: 'https://www.marcus.com/us/en/savings/high-yield-savings',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: 'low',
      featured: true,
      priority: 10,
      active: true,
    },
    {
      name: 'Ally Bank Online Savings Account',
      provider: 'Ally Bank',
      productType: 'savings_account',
      region: 'US',
      interestRate: 5.25,
      apr: null,
      fees: { monthly: 0, minimum: 0, atm_rebate: 10 },
      description: 'Competitive rate with excellent customer service and budgeting tools built in.',
      keyFeatures: [
        '5.25% APY',
        'No monthly maintenance fees',
        'Up to $10/month ATM fee reimbursement',
        'Savings buckets for multiple goals',
        '24/7 customer service',
      ],
      primaryBenefit: 'High interest rate',
      secondaryBenefit: 'Organize savings with buckets for different goals',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.ally.com/bank/online-savings-account/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family', 'investment'],
      riskLevel: 'low',
      featured: true,
      priority: 9,
      active: true,
    },
    {
      name: 'American Express High Yield Savings',
      provider: 'American Express',
      productType: 'savings_account',
      region: 'US',
      interestRate: 5.35,
      apr: null,
      fees: { monthly: 0, minimum: 0 },
      description: 'Backed by a trusted brand with competitive rates and excellent mobile app.',
      keyFeatures: [
        '5.35% APY',
        'No fees whatsoever',
        'No minimum balance',
        'Instant transfers to other banks',
        'Excellent mobile app',
      ],
      primaryBenefit: 'Great rate with trusted brand',
      secondaryBenefit: 'Easy-to-use app encourages regular saving',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.americanexpress.com/en-us/banking/online-savings/overview/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: 'low',
      featured: false,
      priority: 8,
      active: true,
    },

    // ISAs (UK)
    {
      name: 'Moneybox Lifetime ISA',
      provider: 'Moneybox',
      productType: 'isa',
      region: 'UK',
      interestRate: 4.25,
      apr: null,
      fees: { monthly: 0, management: 0.45 },
      description: 'Government adds 25% bonus to your savings (up to £1,000/year). Perfect for first-time home buyers.',
      keyFeatures: [
        '25% government bonus (up to £1,000/year)',
        '4.25% interest rate',
        'Save up to £4,000/year',
        'Use for first home or retirement',
        'Round-up feature to save spare change',
      ],
      primaryBenefit: 'Free £1,000/year from government',
      secondaryBenefit: 'Automatic round-ups build saving habit',
      minDeposit: 1,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'UK residents aged 18-39, first-time home buyers',
      applicationUrl: 'https://www.moneyboxapp.com/lifetime-isa/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house'],
      riskLevel: 'low',
      featured: true,
      priority: 10,
      active: true,
    },
    {
      name: 'Plum Cash ISA',
      provider: 'Plum',
      productType: 'isa',
      region: 'UK',
      interestRate: 5.17,
      apr: null,
      fees: { monthly: 0 },
      description: 'Highest rate Cash ISA with AI-powered automatic saving based on your spending patterns.',
      keyFeatures: [
        '5.17% AER fixed rate',
        'AI analyzes spending and auto-saves',
        'Tax-free interest',
        'Flexible withdrawals',
        '£20,000 annual allowance',
      ],
      primaryBenefit: 'Top ISA rate (5.17%)',
      secondaryBenefit: 'AI automation removes willpower from saving',
      minDeposit: 1,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'UK residents 18+',
      applicationUrl: 'https://withplum.com/savings/interest/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: 'low',
      featured: true,
      priority: 9,
      active: true,
    },

    // Credit Builder Cards
    {
      name: 'Discover it® Student Cash Back',
      provider: 'Discover',
      productType: 'credit_card',
      region: 'US',
      interestRate: null,
      apr: 21.49,
      fees: { annual: 0, foreign_transaction: 0, late: 41 },
      description: 'Build credit while earning rewards. 5% cash back on rotating categories, plus Cashback Match in year one.',
      keyFeatures: [
        '5% cash back rotating categories (up to $1,500/quarter)',
        '1% cash back on everything else',
        'Cashback Match - Discover matches all cashback year one',
        'Free FICO credit score',
        'No annual fee',
      ],
      primaryBenefit: 'Build credit score',
      secondaryBenefit: 'Earn cash back on everyday purchases (effectively 10% first year)',
      minDeposit: null,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'Students with limited or no credit history',
      applicationUrl: 'https://www.discover.com/credit-cards/student/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['travel', 'family'],
      riskLevel: null,
      featured: true,
      priority: 8,
      active: true,
    },
    {
      name: 'Petal® 2 "Cash Back, No Fees" Visa® Credit Card',
      provider: 'Petal',
      productType: 'credit_card',
      region: 'US',
      interestRate: null,
      apr: 19.99,
      fees: { annual: 0, foreign_transaction: 0, late: 0 },
      description: 'Perfect for building credit with no credit check. Earn cash back and track spending in app.',
      keyFeatures: [
        '1-1.5% cash back on purchases',
        'No annual fee',
        'No late fees or foreign transaction fees',
        'Reports to all 3 credit bureaus',
        'Spending tracker and budgeting tools',
      ],
      primaryBenefit: 'Build credit with no credit history',
      secondaryBenefit: 'Built-in budgeting tools develop financial habits',
      minDeposit: null,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'No credit history required, uses bank account history',
      applicationUrl: 'https://www.petalcard.com/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['travel', 'family', 'house'],
      riskLevel: null,
      featured: true,
      priority: 7,
      active: true,
    },

    // Student Checking Accounts
    {
      name: 'Chase College Checking℠',
      provider: 'Chase',
      productType: 'checking_account',
      region: 'US',
      interestRate: 0.01,
      apr: null,
      fees: { monthly: 0, minimum: 0, overdraft: 34 },
      description: 'No monthly fees for up to 5 years while in college. $100 bonus for opening account.',
      keyFeatures: [
        'No monthly fees (up to 5 years)',
        '$100 bonus when opening',
        'Free checks',
        'Mobile check deposit',
        'Access to 16,000 ATMs nationwide',
      ],
      primaryBenefit: 'Free banking with $100 signup bonus',
      secondaryBenefit: 'Learn banking basics with a major institution',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'Students aged 17-24 enrolled in college',
      applicationUrl: 'https://www.chase.com/personal/checking/student-checking',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['travel', 'family'],
      riskLevel: null,
      featured: false,
      priority: 6,
      active: true,
    },

    // Investment Platforms
    {
      name: 'Fidelity Go®',
      provider: 'Fidelity',
      productType: 'investment_platform',
      region: 'US',
      interestRate: null,
      apr: null,
      fees: { management: 0, advisory_over_10k: 0.35 },
      description: 'Robo-advisor that automatically invests and rebalances your portfolio. Free for balances under $25k.',
      keyFeatures: [
        'Free advisory for balances under $25k',
        'Automatic rebalancing',
        'Professionally managed portfolios',
        'No account minimum',
        'Tax-smart investing strategies',
      ],
      primaryBenefit: 'Grow wealth through investing',
      secondaryBenefit: 'Hands-off automation removes barriers to investing',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.fidelity.com/managed-accounts/fidelity-go/overview',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['investment', 'family'],
      riskLevel: 'medium',
      featured: true,
      priority: 8,
      active: true,
    },
    {
      name: 'Betterment Investing',
      provider: 'Betterment',
      productType: 'investment_platform',
      region: 'US',
      interestRate: null,
      apr: null,
      fees: { management: 0.25, premium: 0.65 },
      description: 'Automated investing with goal-based portfolios. Tax-loss harvesting and automatic rebalancing included.',
      keyFeatures: [
        '0.25% annual fee',
        'Goal-based investing',
        'Automatic rebalancing',
        'Tax-loss harvesting',
        'Financial advisor access (Premium)',
      ],
      primaryBenefit: 'Automated wealth building',
      secondaryBenefit: 'Goal tracking keeps you motivated',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.betterment.com/investing',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['investment', 'family', 'house'],
      riskLevel: 'medium',
      featured: true,
      priority: 7,
      active: true,
    },
    {
      name: 'Vanguard Total Stock Market Index Fund (VTSAX)',
      provider: 'Vanguard',
      productType: 'investment_platform',
      region: 'US',
      interestRate: null,
      apr: null,
      fees: { expense_ratio: 0.04 },
      description: 'Own a piece of the entire US stock market with one of the lowest-cost funds available.',
      keyFeatures: [
        'Just 0.04% expense ratio',
        'Diversification across 4,000+ stocks',
        'Long-term average return: 10% annually',
        'Perfect for buy-and-hold strategy',
        'Automatic dividend reinvestment',
      ],
      primaryBenefit: 'Long-term wealth growth',
      secondaryBenefit: 'Set-it-and-forget-it simplicity builds discipline',
      minDeposit: 3000,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+, $3,000 minimum',
      applicationUrl: 'https://investor.vanguard.com/investment-products/mutual-funds/profile/vtsax',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['investment', 'family'],
      riskLevel: 'medium',
      featured: true,
      priority: 9,
      active: true,
    },

    // UK Investment Platforms
    {
      name: 'Nutmeg Stocks & Shares ISA',
      provider: 'Nutmeg',
      productType: 'isa',
      region: 'UK',
      interestRate: null,
      apr: null,
      fees: { management: 0.75 },
      description: 'Invest your ISA allowance tax-free. Choose your risk level and let Nutmeg handle the rest.',
      keyFeatures: [
        'Tax-free investment growth',
        '10 risk levels to choose from',
        'Automatic rebalancing',
        'No platform fee on first £100k',
        'Socially responsible portfolios available',
      ],
      primaryBenefit: 'Tax-free investment growth',
      secondaryBenefit: 'Automated management removes complexity',
      minDeposit: 100,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'UK residents 18+',
      applicationUrl: 'https://www.nutmeg.com/stocks-and-shares-isa',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['investment', 'family', 'house'],
      riskLevel: 'medium',
      featured: true,
      priority: 8,
      active: true,
    },

    // Additional Products
    {
      name: 'SoFi Checking and Savings',
      provider: 'SoFi',
      productType: 'savings_account',
      region: 'US',
      interestRate: 4.6,
      apr: null,
      fees: { monthly: 0, atm: 0 },
      description: 'High-yield savings with checking account combo. Get paid up to 2 days early with direct deposit.',
      keyFeatures: [
        '4.6% APY on savings',
        'No account fees',
        'Get paid up to 2 days early',
        '55,000+ fee-free ATMs',
        'Financial planning tools included',
      ],
      primaryBenefit: 'High interest rate on savings',
      secondaryBenefit: 'Early payday helps with cash flow management',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.sofi.com/banking/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: 'low',
      featured: false,
      priority: 7,
      active: true,
    },
    {
      name: 'Capital One 360 Performance Savings',
      provider: 'Capital One',
      productType: 'savings_account',
      region: 'US',
      interestRate: 4.35,
      apr: null,
      fees: { monthly: 0 },
      description: 'Solid rate with easy mobile banking. Create multiple savings goals in one account.',
      keyFeatures: [
        '4.35% APY',
        'No fees or minimums',
        'Create up to 25 savings goals',
        '70,000+ fee-free ATMs',
        'Mobile check deposit',
      ],
      primaryBenefit: 'Good interest rate',
      secondaryBenefit: 'Multiple savings goals help organize financial priorities',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.capitalone.com/bank/savings-accounts/online-performance-savings-account/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: 'low',
      featured: false,
      priority: 6,
      active: true,
    },
    {
      name: 'Acorns Invest',
      provider: 'Acorns',
      productType: 'investment_platform',
      region: 'US',
      interestRate: null,
      apr: null,
      fees: { monthly: 3 },
      description: 'Micro-investing app that rounds up purchases and invests spare change automatically.',
      keyFeatures: [
        'Round-up spare change to invest',
        'Automatic recurring investments',
        'Portfolio rebalancing',
        'Educational content',
        'Found Money cashback from partners',
      ],
      primaryBenefit: 'Start investing with spare change',
      secondaryBenefit: 'Painless automation makes investing effortless',
      minDeposit: 5,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+',
      applicationUrl: 'https://www.acorns.com/invest/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['investment', 'family'],
      riskLevel: 'medium',
      featured: false,
      priority: 6,
      active: true,
    },
    {
      name: 'Monzo Plus Account',
      provider: 'Monzo',
      productType: 'checking_account',
      region: 'UK',
      interestRate: 4.0,
      apr: null,
      fees: { monthly: 5 },
      description: 'Digital bank with powerful budgeting tools and 4% interest on balance up to £2,000.',
      keyFeatures: [
        '4% AER on balance up to £2,000',
        'Advanced budgeting features',
        'Instant spending notifications',
        'Pots for saving goals',
        'Virtual cards for online shopping',
      ],
      primaryBenefit: 'Earn interest on everyday spending account',
      secondaryBenefit: 'Built-in budgeting makes saving automatic',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'UK residents 18+',
      applicationUrl: 'https://monzo.com/i/plus',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: null,
      featured: true,
      priority: 7,
      active: true,
    },
    {
      name: 'Starling Bank Kite Account',
      provider: 'Starling Bank',
      productType: 'checking_account',
      region: 'UK',
      interestRate: 3.25,
      apr: null,
      fees: { monthly: 0 },
      description: 'Award-winning banking app with Savings Spaces and automatic round-up saving.',
      keyFeatures: [
        '3.25% AER on balance',
        'Create Savings Spaces for goals',
        'Round-up purchases to save',
        'Fee-free spending abroad',
        'Real-time spending insights',
      ],
      primaryBenefit: 'Interest on everyday account',
      secondaryBenefit: 'Savings Spaces visualize progress toward multiple goals',
      minDeposit: 0,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'UK residents 18+',
      applicationUrl: 'https://www.starlingbank.com/kite/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: null,
      featured: true,
      priority: 8,
      active: true,
    },
    {
      name: 'CIT Bank Platinum Savings',
      provider: 'CIT Bank',
      productType: 'savings_account',
      region: 'US',
      interestRate: 5.05,
      apr: null,
      fees: { monthly: 0 },
      description: 'Strong interest rate with easy online management and mobile app.',
      keyFeatures: [
        '5.05% APY',
        'No monthly fees',
        'Mobile app for easy access',
        'Automatic savings plan',
        'FDIC insured',
      ],
      primaryBenefit: 'Competitive 5.05% rate',
      secondaryBenefit: 'Automatic savings plan builds consistency',
      minDeposit: 100,
      minIncome: null,
      minCreditScore: null,
      eligibilityNotes: 'US residents 18+, $100 minimum',
      applicationUrl: 'https://www.cit.com/cit-bank/savings/platinum-savings/',
      imageUrl: null,
      logoUrl: null,
      suitableForGoals: ['house', 'travel', 'wedding', 'family'],
      riskLevel: 'low',
      featured: false,
      priority: 7,
      active: true,
    },
  ];

  console.log('Creating financial products...');
  let created = 0;

  for (const product of products) {
    await prisma.financialProduct.create({
      data: product,
    });
    created++;
  }

  console.log(`✓ Created ${created} financial products\n`);

  // Summary
  console.log('📊 Seeding Summary:');
  console.log(`   Total Products: ${created}`);
  console.log(`   Savings Accounts: ${products.filter(p => p.productType === 'savings_account').length}`);
  console.log(`   ISAs (UK): ${products.filter(p => p.productType === 'isa').length}`);
  console.log(`   Credit Cards: ${products.filter(p => p.productType === 'credit_card').length}`);
  console.log(`   Checking Accounts: ${products.filter(p => p.productType === 'checking_account').length}`);
  console.log(`   Investment Platforms: ${products.filter(p => p.productType === 'investment_platform').length}`);
  console.log(`   Featured Products: ${products.filter(p => p.featured).length}`);
  console.log('\n✅ Financial products seeding completed!');
  console.log('\n💡 Tips:');
  console.log('   - Products emphasize "two-for-one deals" (help goal + build habits)');
  console.log('   - Use /api/products/recommendations to get personalized matches');
  console.log('   - Users can browse all products at /products page');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
